inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
    - 'app/controllers/concerns/action_controller/**/*'

Rails:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/requests/file_auth_request_spec.rb'
    - 'spec/requests/iiif_auth_request_spec.rb'
    - 'spec/requests/media_auth_request_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/iiif_controller.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/requests/file_auth_request_spec.rb'
    - 'spec/requests/iiif_auth_request_spec.rb'
    - 'spec/requests/media_auth_request_spec.rb'
    - 'spec/routing/iiif_routing_spec.rb'
    - 'spec/routing/legacy_image_api_spec.rb'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  NamePrefix:
    - 'is_'

Style/StringLiterals:
  Enabled: false
