inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
    - 'app/controllers/concerns/action_controller/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/requests/file_auth_request_spec.rb'
    - 'spec/requests/iiif_auth_request_spec.rb'
    - 'spec/requests/media_auth_request_spec.rb'

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/requests/file_auth_request_spec.rb'
    - 'spec/requests/iiif_auth_request_spec.rb'
    - 'spec/requests/media_auth_request_spec.rb'

Style/StringLiterals:
  Enabled: false
