stacks:
  storage_root: /stacks
  djatoka_url: 'http://imageserver-b.stanford.edu/adore-djatoka/resolver'

purl:
  url: 'https://purl.stanford.edu/'

user:
  stanford_groups:
    - stanford:stanford
    - stanford:academic
    - stanford:administrative
    - organization:sumc
    - sulair:proxy-access
    - lane:proxy-access
