stacks:
  storage_root: /stacks
  djatoka_url: 'http://imageserver-b.stanford.edu/adore-djatoka/resolver'

purl:
  url: 'https://purl.stanford.edu/'

stream:
  # max_token_age is specified in seconds
  max_token_age: 45

# non-IIIF images
legacy:
  sizes:
    - square
    - thumb
    - small
    - medium
    - large
    - xlarge
    - full

user:
  stanford_groups:
    - stanford:stanford
    - stanford:academic
    - stanford:administrative
    - organization:sumc
    - sulair:proxy-access
    - lane:proxy-access
  locations:
    spec:
      - an.ip.address

cors:
  allow_origin_url: 'https://embed.stanford.edu'
features:
  streaming_media: false
  location_auth: false
