stacks:
  storage_root: /stacks
  driver: djatoka
  djatoka:
    image:
      implementation: DjatokaImage
      attributes:
        url: 'http://localhost:8080/resolver'
    metadata:
      implementation: DjatokaMetadataService
    check:
      implementation: CheckDjatoka

purl:
  url: 'https://purl.stanford.edu/'

stream:
  # max_token_age is specified in seconds
  max_token_age: 45

# non-IIIF images
legacy:
  sizes:
    - square
    - thumb
    - small
    - medium
    - large
    - xlarge
    - full

user:
  stanford_groups:
    - stanford:stanford
    - stanford:academic
    - stanford:administrative
    - organization:sumc
    - sulair:proxy-access
    - lane:proxy-access
  locations:
    spec:
      - an.ip.address

cors:
  allow_origin_url: 'https://embed.stanford.edu'
features:
  streaming_media: true
