stacks:
  storage_root: /stacks
  djatoka_url: 'http://localhost:8080/resolver'
  driver: remote_iiif
  djatoka:
    image: DjatokaImage
    info: DjatokaInfoService
  remote_iiif:
    image: IiifImage
    info: IiifMetadataService
    attributes:
      # Example: https://sul-imageserver-uat.stanford.edu/cantaloupe/iiif/2/ff%2F139%2Fpd%2F0160%2F67352ccc-d1b0-11e1-89ae-279075081939.jp2/info.json
      base_uri: https://sul-imageserver-uat.stanford.edu/cantaloupe/iiif/2/

purl:
  url: 'https://purl.stanford.edu/'

stream:
  # max_token_age is specified in seconds
  max_token_age: 45

# non-IIIF images
legacy:
  sizes:
    - square
    - thumb
    - small
    - medium
    - large
    - xlarge
    - full

user:
  stanford_groups:
    - stanford:stanford
    - stanford:academic
    - stanford:administrative
    - organization:sumc
    - sulair:proxy-access
    - lane:proxy-access
  locations:
    spec:
      - an.ip.address

cors:
  allow_origin_url: 'https://embed.stanford.edu'
features:
  streaming_media: true
