stacks:
  storage_root: /stacks
  djatoka_url: 'http://imageserver-b.stanford.edu/adore-djatoka/resolver'

purl:
  url: 'https://purl.stanford.edu/'

stream:
  url: http://streaming-server.com:1935/stuff
  # streaming media file extensions we support
  video:
    - mov
    - mp4
    - mpeg
  audio:
    - mp3

# non-IIIF images
legacy:
  sizes:
    - square
    - thumb
    - small
    - medium
    - large
    - xlarge
    - full

user:
  stanford_groups:
    - stanford:stanford
    - stanford:academic
    - stanford:administrative
    - organization:sumc
    - sulair:proxy-access
    - lane:proxy-access
