app_users:
  test-user: 'password'

user:
  locations:
    location1:
      - ip.address1
      - ip.address2
    location2:
      - ip.address3
      - ip.address4

max_pixels: 8000000 # Similar to cantaloupe.properties
